# Generated by Django 5.0.6 on 2024-06-15 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='cnpj',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='destinations.entidade'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='contatos',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='fones',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='nf',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
