# Generated by Django 5.0.6 on 2024-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='ativo',
            field=models.CharField(default='s', max_length=1),
        ),
    ]
