# Generated by Django 5.0.6 on 2024-07-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_entidade_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='nf',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
