# Generated by Django 5.0.6 on 2024-06-15 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_destino_cnpj_alter_entidade_contatos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destino',
            new_name='Lancamento',
        ),
    ]
