# Generated by Django 5.0.6 on 2024-07-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_entidade_nf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='contatos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
