# Generated by Django 5.0.6 on 2024-06-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_rename_destino_lancamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='lancamento',
            name='unid',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
