# Generated by Django 5.0.6 on 2024-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_alter_entidade_contatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='fones',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
