# Generated by Django 5.0.6 on 2024-06-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0004_registrolancamento_lancamento_unid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistroLancamento',
            new_name='RegistroLancamentos',
        ),
    ]
