# Generated by Django 5.0.6 on 2024-07-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_rename_registrolancamento_registrolancamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.IntegerField(help_text='Este campo não pode ficar vazio', primary_key=True, serialize=False),
        ),
    ]
