# Generated by Django 5.0.6 on 2024-07-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_alter_entidade_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.IntegerField(error_messages={'invalid': 'CNPJ só pode ter números', 'required': 'O CNPJ não pode ficar vazio'}, help_text='Este campo não pode ficar vazio', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='rs',
            field=models.CharField(error_messages={'required': 'A razão social não pode ficar vazia'}, max_length=50),
        ),
    ]
