# Generated by Django 5.0.6 on 2024-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_alter_entidade_cnpj_alter_entidade_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cnpj',
            field=models.IntegerField(blank=True, help_text='Este campo não pode ficar vazio', primary_key=True, serialize=False),
        ),
    ]
