# Generated by Django 5.0.6 on 2024-07-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0008_alter_entidade_cnpj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='rs',
            field=models.CharField(max_length=50),
        ),
    ]
