# Generated by Django 5.0.6 on 2024-07-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0009_alter_entidade_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='rs',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
